version: '3.6'

services:
  db-covid19:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api_covid19
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
    expose:
      - 3306

  api-covid19:
    build: .
    image: api-covid19:latest
    ports:
      - 8080:8080
    depends_on:
      - "db-covid19"
    command: sh -c "/wait && /api-covid19"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-covid19/api_covid19?serverTimezone=UTC&autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
